name: GitHub action to retrieve Zotero collection in BibLaTeX format and save it as GitHub repository

on:
  schedule:
    - cron: "0 8,12,18 * * *"
  push:
    branches:
      - test
  workflow_dispatch:
  
jobs:
  zotero-bib-to-gh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Run
        run: uv run zotero-bib-to-gh.py
        env:
          ZOTERO_USER_ID: ${{ secrets.ZOTERO_USER_ID }}
          ZOTERO_BEARER_TOKEN: ${{ secrets.ZOTERO_BEARER_TOKEN }}

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          echo `git add -A && git commit -m "Add changes"`

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
